# 量子太空杀项目资金支持

# GitHub Sponsors (英文社区)
github: acb666

# Patreon支持
patreon: QuantumSpaceWar

# Open Collective支持
open_collective: quantumspacewar

# Ko-fi支持
ko_fi: quantumspacewar

# Tidelift支持
tidelift: npm/quantumspacewar

# Community Bridge支持
community_bridge: quantum-space-war

# Liberapay支持
liberapay: quantumspacewar

# IssueHunt支持
issuehunt: quantumspacewar

# LFX Crowdfunding支持
lfx_crowdfunding: quantum-space-war

# Polar支持
polar: quantumspacewar

# Buy Me a Coffee支持
buy_me_a_coffee: quantumspacewar

# thanks.dev支持
thanks_dev: acb666

# 自定义资金支持链接（中文用户）
custom:
  - `https://github.com/acb666/QuantumSpaceWar`  # GitHub项目主页
  - `https://afdian.com/a/quantumspacewar`  # 爱发电支持
  - `https://patreon.com/CO2_just_me`  # Patreon中文用户支持
