# Generated by Django 5.2.8 on 2025-11-21 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('strategy', '战术策略'), ('guide', '新手指南'), ('advanced', '高级技巧'), ('discussion', '讨论交流'), ('other', '其他')], default='other', max_length=20, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='guide',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=200, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='guide',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='标题'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['author', '-created_at'], name='guides_guid_author__d3ba1e_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['category', '-created_at'], name='guides_guid_categor_3a8d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['is_published', '-created_at'], name='guides_guid_is_publ_f67045_idx'),
        ),
    ]
