# Generated by Django 5.2.8 on 2025-12-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_category_guide_is_published_guide_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('room_name', models.CharField(default='general', max_length=100, verbose_name='聊天室名称')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息列表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_name', '-created_at'], name='guides_chat_room_na_bd0a56_idx'), models.Index(fields=['sender', '-created_at'], name='guides_chat_sender__e4258d_idx')],
            },
        ),
    ]
