# Generated by Django 5.2.8 on 2025-12-05 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, max_length=500, verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等级')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='游戏场次')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='胜利场次')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': '聊天消息', 'verbose_name_plural': '聊天消息'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-created_at'], 'verbose_name': '攻略', 'verbose_name_plural': '攻略'},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='guides_chat_room_na_bd0a56_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='guides_chat_sender__e4258d_idx',
        ),
        migrations.RemoveIndex(
            model_name='guide',
            name='guides_guid_author__d3ba1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='guide',
            name='guides_guid_categor_3a8d6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='guide',
            name='guides_guid_is_publ_f67045_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='is_published',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='guide',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_guides', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(choices=[('general', '综合讨论'), ('strategy', '攻略交流'), ('newbie', '新手指导'), ('team', '组队开黑')], default='general', max_length=50, verbose_name='聊天室'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('beginner', '新手入门'), ('strategy', '进阶攻略'), ('advanced', '高级技巧'), ('character', '角色分析'), ('equipment', '装备指南'), ('team', '团队配合'), ('other', '其他')], default='other', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
